[package]
name = "michi-rust"
version = "0.1.0"
edition = "2024"

[features]
default = ["board9x9"]
board9x9 = []
board13x13 = []

[dependencies]
clap = { version = "4", features = ["derive"] }
fastrand = "2"
